---

cf-params: &cf-params
      CF_API_URL: ((cf_it_api_url))
      CF_USERNAME: ((cf_it_username))
      CF_PASSWORD: ((cf_it_password))
      CF_ORG: ((cf_it_org))
      CF_SKIP_SSL: ((cf_it_skip_ssl))
      CF_SPACE: ((cf_it_space))
      CF_APP_DOMAIN: ((cf_it_app_domain))

resources:

- name: source
  type: git
  source:
    uri: https://github.com/cloudfoundry/developer-training-class-apps.git
    branch: master
    paths: [rest-data-service/*,ci/solution_setup.sh]
    depth: 1

- name: jar
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: rest-data-service.jar
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))

jobs:

- name: build
  plan:
  - get: source
    trigger: true
  - task: mvn-clean-package
    file: source/rest-data-service/ci/tasks/mvn-clean-package.yml
  - task: test-rest-data-service
    file: source/rest-data-service/ci/tasks/test.yml
    params: *cf-params
    on_failure:
      task: cleanup
      file: source/rest-data-service/ci/tasks/cleanup.yml
      params:
        << : *cf-params
  - task: cleanup
    file: source/rest-data-service/ci/tasks/cleanup.yml
    params:
      << : *cf-params
  - put: jar
    params:
      file: artifacts/rest-data-service.jar
