---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/gradle
    tag: 'latest'

inputs:
- name: uaa-source
- name: source

outputs:
- name: artifacts

run:
  path: source/uaa/ci/tasks/build.sh
