---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli-ruby
    tag: 'latest'

inputs:
- name: web-ui
- name: uaa-war
- name: uaa-war-manifest

run:
  path: apps/web-ui/ci/scripts/system-tests.sh
  dir: web-ui

params:
  CF_API_URL:
  CF_USER_NAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SKIP_SSL:
  CF_SPACE:
