---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli-ruby
    tag: 'latest'

inputs:
- name: source
- name: uaa-war
- name: uaa-war-manifest

run:
  path: source/ci/tasks/system-tests.sh
