---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/golang-image
    tag: 'latest'

inputs:
- name: source

outputs:
- name: artifacts

run:
  path: source/uaa-guard-proxy/ci/tasks/create-zip.sh
