---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: worker-app
- name: rest-data-service-jar

run:
  path: apps/worker/ci/scripts/system-test-worker.sh
  dir: worker-app

params:
  CF_API_URL:
  CF_USER_NAME:
  CF_PASSWORD:
  CF_ORG:
  CF_SKIP_SSL:
  CF_SPACE:
