---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: ruby
    tag: '2.4.0'

inputs:
- name: worker-app

run:
  path: apps/worker/ci/scripts/test-worker-app.sh
  dir: worker-app
