---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.3-jdk-8'

inputs:
- name: rate-limiter-src

outputs:
- name: updated-repo

run:
  path: bash
  args:
  - -exc
  - |
    git clone rate-limiter-src updated-repo
    pushd updated-repo/apps/rate-limit-route-service
      mvn clean package
    popd
