---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: maven
    tag: '3.3-jdk-8'

inputs:
- name: source

outputs:
- name: artifacts

run:
  path: source/rest-data-service/ci/tasks/mvn-clean-package.sh
