---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: rscale/cf-cli
    tag: 'latest'

inputs:
- name: source
- name: artifacts

run:
  path: source/rest-data-service/ci/tasks/test.sh
