

resources:

- name: source
  type: git
  source:
    uri: https://github.com/cloudfoundry/developer-training-class-apps.git
    branch: master
    paths: [uaa-guard-proxy/*]
    depth: 1

- name: zip
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: uaa-guard-proxy.zip
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))


jobs:

- name: package
  serial: true
  plan:
  - get: source
    trigger: true
  - task: create-zip
    file: source/uaa-guard-proxy/ci/tasks/create-zip.yml
  - put: zip
    params:
      file: artifacts/uaa-guard-proxy.zip
