---
cf-params: &cf-params
      CF_API_URL: ((cf_api_url))
      CF_USER_NAME: ((cf_user_name))
      CF_PASSWORD: ((cf_password))
      CF_ORG: ((cf_org))
      CF_SKIP_SSL: ((cf_skip_ssl))
      CF_SPACE: ((cf_space))

resources:

- name: ci-tasks
  type: git
  source:
    uri: https://github.com/cloudfoundry/developer-training-class-apps.git
    branch: master
    paths: [ci/tasks/*]

- name: rate-limit-route-service-source
  type: git
  source:
    uri: https://github.com/cloudfoundry/developer-training-class-apps.git
    branch: master
    paths: [rate-limit-route-service/*]

- name: rate-limiter-jar
  type: s3
  source:
    bucket: ((assets_bucket_name))
    region_name: ((assets_bucket_region))
    versioned_file: rate-limit-route-service.jar
    access_key_id: ((aws_access_key_id))
    secret_access_key: ((aws_secret_access_key))



jobs:

- name: build-rate-limiter
  plan:
  - get: rate-limit-route-service-source
    trigger: true
  - get: ci-tasks
  - task: build-rate-limiter
    file: ci-tasks/ci/tasks/mvn-clean-package.yml
    params:
      APP_PATH: rate-limit-route-service-source
  - put: rate-limiter-jar
    params:
      file: artifacts/rate-limit-route-service.jar
